### ISSUE TITLE
Only stm32f4?

### ISSUE THREAD

**Issue by avaldebe** [alvarop/silta#7]
Does it have to be a F4? Does it fit in a F1 (eg blue pill)?

**Comment by alvarop** [comment]
It should be able to, it's pretty small. You'd have to re-write the drivers for each peripheral though :(

**Comment by avaldebe** [comment]
As my first ARM project, I suspect I won't finish it the port.
Fortunately my [BMP reward][BMP] arrived today, including 2x[1bitsy][] (STM32F415RGT6)...

PS:
Thanks for answering

[BMP]: https://www.kickstarter.com/projects/esden/1bitsy-and-black-magic-probe-demystifying-arm-prog
[1bitsy]: https://1bitsquared.com/collections/embedded-hardware/products/1bitsy
